/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as MultimediaRouteImport } from './routes/multimedia'
import { Route as SociosRouteImport } from './routes/socios'
import { Route as ClubeIndexRouteImport } from './routes/clube.index'
import { Route as ClubeEstadioRouteImport } from './routes/clube.estadio'
import { Route as ClubeHistoriaRouteImport } from './routes/clube.historia'
import { Route as ClubeInstitucionalRouteImport } from './routes/clube.institucional'
import { Route as ClubePresidenteRouteImport } from './routes/clube.presidente'
import { Route as FutebolIndexRouteImport } from './routes/futebol.index'
import { Route as ModalidadesIndexRouteImport } from './routes/modalidades.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as PaginasSlugRouteImport } from './routes/paginas.$slug'
import { Route as FutebolEquipaIndexRouteImport } from './routes/futebol.$equipa.index'
import { Route as FutebolEquipaJogadorRouteImport } from './routes/futebol.$equipa.$jogador'
import { Route as ModalidadesModalidadeIndexRouteImport } from './routes/modalidades.$modalidade.index'
import { Route as ModalidadesModalidadeAtletaRouteImport } from './routes/modalidades.$modalidade.$atleta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const MultimediaRoute = MultimediaRouteImport.update({
  id: '/multimedia',
  path: '/multimedia',
  getParentRoute: () => rootRouteImport,
} as any)
const SociosRoute = SociosRouteImport.update({
  id: '/socios',
  path: '/socios',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeIndexRoute = ClubeIndexRouteImport.update({
  id: '/clube/',
  path: '/clube/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeEstadioRoute = ClubeEstadioRouteImport.update({
  id: '/clube/estadio',
  path: '/clube/estadio',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeHistoriaRoute = ClubeHistoriaRouteImport.update({
  id: '/clube/historia',
  path: '/clube/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeInstitucionalRoute = ClubeInstitucionalRouteImport.update({
  id: '/clube/institucional',
  path: '/clube/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubePresidenteRoute = ClubePresidenteRouteImport.update({
  id: '/clube/presidente',
  path: '/clube/presidente',
  getParentRoute: () => rootRouteImport,
} as any)
const FutebolIndexRoute = FutebolIndexRouteImport.update({
  id: '/futebol/',
  path: '/futebol/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalidadesIndexRoute = ModalidadesIndexRouteImport.update({
  id: '/modalidades/',
  path: '/modalidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginasSlugRoute = PaginasSlugRouteImport.update({
  id: '/paginas/$slug',
  path: '/paginas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FutebolEquipaIndexRoute = FutebolEquipaIndexRouteImport.update({
  id: '/futebol/$equipa/',
  path: '/futebol/$equipa/',
  getParentRoute: () => rootRouteImport,
} as any)
const FutebolEquipaJogadorRoute = FutebolEquipaJogadorRouteImport.update({
  id: '/futebol/$equipa/$jogador',
  path: '/futebol/$equipa/$jogador',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalidadesModalidadeIndexRoute =
  ModalidadesModalidadeIndexRouteImport.update({
    id: '/modalidades/$modalidade/',
    path: '/modalidades/$modalidade/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModalidadesModalidadeAtletaRoute =
  ModalidadesModalidadeAtletaRouteImport.update({
    id: '/modalidades/$modalidade/$atleta',
    path: '/modalidades/$modalidade/$atleta',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/contactos': typeof ContactosRoute
  '/corporate': typeof CorporateRoute
  '/multimedia': typeof MultimediaRoute
  '/socios': typeof SociosRoute
  '/clube/estadio': typeof ClubeEstadioRoute
  '/clube/historia': typeof ClubeHistoriaRoute
  '/clube/institucional': typeof ClubeInstitucionalRoute
  '/clube/presidente': typeof ClubePresidenteRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/paginas/$slug': typeof PaginasSlugRoute
  '/clube/': typeof ClubeIndexRoute
  '/futebol/': typeof FutebolIndexRoute
  '/modalidades/': typeof ModalidadesIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/futebol/$equipa/$jogador': typeof FutebolEquipaJogadorRoute
  '/modalidades/$modalidade/$atleta': typeof ModalidadesModalidadeAtletaRoute
  '/futebol/$equipa/': typeof FutebolEquipaIndexRoute
  '/modalidades/$modalidade/': typeof ModalidadesModalidadeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/contactos': typeof ContactosRoute
  '/corporate': typeof CorporateRoute
  '/multimedia': typeof MultimediaRoute
  '/socios': typeof SociosRoute
  '/clube/estadio': typeof ClubeEstadioRoute
  '/clube/historia': typeof ClubeHistoriaRoute
  '/clube/institucional': typeof ClubeInstitucionalRoute
  '/clube/presidente': typeof ClubePresidenteRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/paginas/$slug': typeof PaginasSlugRoute
  '/clube': typeof ClubeIndexRoute
  '/futebol': typeof FutebolIndexRoute
  '/modalidades': typeof ModalidadesIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/futebol/$equipa/$jogador': typeof FutebolEquipaJogadorRoute
  '/modalidades/$modalidade/$atleta': typeof ModalidadesModalidadeAtletaRoute
  '/futebol/$equipa': typeof FutebolEquipaIndexRoute
  '/modalidades/$modalidade': typeof ModalidadesModalidadeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/contactos': typeof ContactosRoute
  '/corporate': typeof CorporateRoute
  '/multimedia': typeof MultimediaRoute
  '/socios': typeof SociosRoute
  '/clube/estadio': typeof ClubeEstadioRoute
  '/clube/historia': typeof ClubeHistoriaRoute
  '/clube/institucional': typeof ClubeInstitucionalRoute
  '/clube/presidente': typeof ClubePresidenteRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/paginas/$slug': typeof PaginasSlugRoute
  '/clube/': typeof ClubeIndexRoute
  '/futebol/': typeof FutebolIndexRoute
  '/modalidades/': typeof ModalidadesIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/futebol/$equipa/$jogador': typeof FutebolEquipaJogadorRoute
  '/modalidades/$modalidade/$atleta': typeof ModalidadesModalidadeAtletaRoute
  '/futebol/$equipa/': typeof FutebolEquipaIndexRoute
  '/modalidades/$modalidade/': typeof ModalidadesModalidadeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/contactos'
    | '/corporate'
    | '/multimedia'
    | '/socios'
    | '/clube/estadio'
    | '/clube/historia'
    | '/clube/institucional'
    | '/clube/presidente'
    | '/noticias/$slug'
    | '/paginas/$slug'
    | '/clube/'
    | '/futebol/'
    | '/modalidades/'
    | '/noticias/'
    | '/futebol/$equipa/$jogador'
    | '/modalidades/$modalidade/$atleta'
    | '/futebol/$equipa/'
    | '/modalidades/$modalidade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/contactos'
    | '/corporate'
    | '/multimedia'
    | '/socios'
    | '/clube/estadio'
    | '/clube/historia'
    | '/clube/institucional'
    | '/clube/presidente'
    | '/noticias/$slug'
    | '/paginas/$slug'
    | '/clube'
    | '/futebol'
    | '/modalidades'
    | '/noticias'
    | '/futebol/$equipa/$jogador'
    | '/modalidades/$modalidade/$atleta'
    | '/futebol/$equipa'
    | '/modalidades/$modalidade'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/contactos'
    | '/corporate'
    | '/multimedia'
    | '/socios'
    | '/clube/estadio'
    | '/clube/historia'
    | '/clube/institucional'
    | '/clube/presidente'
    | '/noticias/$slug'
    | '/paginas/$slug'
    | '/clube/'
    | '/futebol/'
    | '/modalidades/'
    | '/noticias/'
    | '/futebol/$equipa/$jogador'
    | '/modalidades/$modalidade/$atleta'
    | '/futebol/$equipa/'
    | '/modalidades/$modalidade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  ContactosRoute: typeof ContactosRoute
  CorporateRoute: typeof CorporateRoute
  MultimediaRoute: typeof MultimediaRoute
  SociosRoute: typeof SociosRoute
  ClubeEstadioRoute: typeof ClubeEstadioRoute
  ClubeHistoriaRoute: typeof ClubeHistoriaRoute
  ClubeInstitucionalRoute: typeof ClubeInstitucionalRoute
  ClubePresidenteRoute: typeof ClubePresidenteRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  PaginasSlugRoute: typeof PaginasSlugRoute
  ClubeIndexRoute: typeof ClubeIndexRoute
  FutebolIndexRoute: typeof FutebolIndexRoute
  ModalidadesIndexRoute: typeof ModalidadesIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  FutebolEquipaJogadorRoute: typeof FutebolEquipaJogadorRoute
  ModalidadesModalidadeAtletaRoute: typeof ModalidadesModalidadeAtletaRoute
  FutebolEquipaIndexRoute: typeof FutebolEquipaIndexRoute
  ModalidadesModalidadeIndexRoute: typeof ModalidadesModalidadeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multimedia': {
      id: '/multimedia'
      path: '/multimedia'
      fullPath: '/multimedia'
      preLoaderRoute: typeof MultimediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socios': {
      id: '/socios'
      path: '/socios'
      fullPath: '/socios'
      preLoaderRoute: typeof SociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/': {
      id: '/clube/'
      path: '/clube'
      fullPath: '/clube/'
      preLoaderRoute: typeof ClubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/estadio': {
      id: '/clube/estadio'
      path: '/clube/estadio'
      fullPath: '/clube/estadio'
      preLoaderRoute: typeof ClubeEstadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/historia': {
      id: '/clube/historia'
      path: '/clube/historia'
      fullPath: '/clube/historia'
      preLoaderRoute: typeof ClubeHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/institucional': {
      id: '/clube/institucional'
      path: '/clube/institucional'
      fullPath: '/clube/institucional'
      preLoaderRoute: typeof ClubeInstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/presidente': {
      id: '/clube/presidente'
      path: '/clube/presidente'
      fullPath: '/clube/presidente'
      preLoaderRoute: typeof ClubePresidenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futebol/': {
      id: '/futebol/'
      path: '/futebol'
      fullPath: '/futebol/'
      preLoaderRoute: typeof FutebolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modalidades/': {
      id: '/modalidades/'
      path: '/modalidades'
      fullPath: '/modalidades/'
      preLoaderRoute: typeof ModalidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paginas/$slug': {
      id: '/paginas/$slug'
      path: '/paginas/$slug'
      fullPath: '/paginas/$slug'
      preLoaderRoute: typeof PaginasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futebol/$equipa/': {
      id: '/futebol/$equipa/'
      path: '/futebol/$equipa'
      fullPath: '/futebol/$equipa/'
      preLoaderRoute: typeof FutebolEquipaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futebol/$equipa/$jogador': {
      id: '/futebol/$equipa/$jogador'
      path: '/futebol/$equipa/$jogador'
      fullPath: '/futebol/$equipa/$jogador'
      preLoaderRoute: typeof FutebolEquipaJogadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modalidades/$modalidade/': {
      id: '/modalidades/$modalidade/'
      path: '/modalidades/$modalidade'
      fullPath: '/modalidades/$modalidade/'
      preLoaderRoute: typeof ModalidadesModalidadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modalidades/$modalidade/$atleta': {
      id: '/modalidades/$modalidade/$atleta'
      path: '/modalidades/$modalidade/$atleta'
      fullPath: '/modalidades/$modalidade/$atleta'
      preLoaderRoute: typeof ModalidadesModalidadeAtletaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  ContactosRoute: ContactosRoute,
  CorporateRoute: CorporateRoute,
  MultimediaRoute: MultimediaRoute,
  SociosRoute: SociosRoute,
  ClubeEstadioRoute: ClubeEstadioRoute,
  ClubeHistoriaRoute: ClubeHistoriaRoute,
  ClubeInstitucionalRoute: ClubeInstitucionalRoute,
  ClubePresidenteRoute: ClubePresidenteRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  PaginasSlugRoute: PaginasSlugRoute,
  ClubeIndexRoute: ClubeIndexRoute,
  FutebolIndexRoute: FutebolIndexRoute,
  ModalidadesIndexRoute: ModalidadesIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  FutebolEquipaJogadorRoute: FutebolEquipaJogadorRoute,
  ModalidadesModalidadeAtletaRoute: ModalidadesModalidadeAtletaRoute,
  FutebolEquipaIndexRoute: FutebolEquipaIndexRoute,
  ModalidadesModalidadeIndexRoute: ModalidadesModalidadeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
