/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as FutebolIndexRouteImport } from './routes/futebol.index'
import { Route as FutebolEquipaIndexRouteImport } from './routes/futebol.$equipa.index'
import { Route as FutebolEquipaJogadorRouteImport } from './routes/futebol.$equipa.$jogador'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const FutebolIndexRoute = FutebolIndexRouteImport.update({
  id: '/futebol/',
  path: '/futebol/',
  getParentRoute: () => rootRouteImport,
} as any)
const FutebolEquipaIndexRoute = FutebolEquipaIndexRouteImport.update({
  id: '/futebol/$equipa/',
  path: '/futebol/$equipa/',
  getParentRoute: () => rootRouteImport,
} as any)
const FutebolEquipaJogadorRoute = FutebolEquipaJogadorRouteImport.update({
  id: '/futebol/$equipa/$jogador',
  path: '/futebol/$equipa/$jogador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/futebol/': typeof FutebolIndexRoute
  '/futebol/$equipa/$jogador': typeof FutebolEquipaJogadorRoute
  '/futebol/$equipa/': typeof FutebolEquipaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/futebol': typeof FutebolIndexRoute
  '/futebol/$equipa/$jogador': typeof FutebolEquipaJogadorRoute
  '/futebol/$equipa': typeof FutebolEquipaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/noticias': typeof NoticiasRoute
  '/futebol/': typeof FutebolIndexRoute
  '/futebol/$equipa/$jogador': typeof FutebolEquipaJogadorRoute
  '/futebol/$equipa/': typeof FutebolEquipaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/noticias'
    | '/futebol/'
    | '/futebol/$equipa/$jogador'
    | '/futebol/$equipa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/noticias'
    | '/futebol'
    | '/futebol/$equipa/$jogador'
    | '/futebol/$equipa'
  id:
    | '__root__'
    | '/'
    | '/noticias'
    | '/futebol/'
    | '/futebol/$equipa/$jogador'
    | '/futebol/$equipa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoticiasRoute: typeof NoticiasRoute
  FutebolIndexRoute: typeof FutebolIndexRoute
  FutebolEquipaJogadorRoute: typeof FutebolEquipaJogadorRoute
  FutebolEquipaIndexRoute: typeof FutebolEquipaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futebol/': {
      id: '/futebol/'
      path: '/futebol'
      fullPath: '/futebol/'
      preLoaderRoute: typeof FutebolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futebol/$equipa/': {
      id: '/futebol/$equipa/'
      path: '/futebol/$equipa'
      fullPath: '/futebol/$equipa/'
      preLoaderRoute: typeof FutebolEquipaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futebol/$equipa/$jogador': {
      id: '/futebol/$equipa/$jogador'
      path: '/futebol/$equipa/$jogador'
      fullPath: '/futebol/$equipa/$jogador'
      preLoaderRoute: typeof FutebolEquipaJogadorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoticiasRoute: NoticiasRoute,
  FutebolIndexRoute: FutebolIndexRoute,
  FutebolEquipaJogadorRoute: FutebolEquipaJogadorRoute,
  FutebolEquipaIndexRoute: FutebolEquipaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
